import './globals.css'
import type { Metadata } from 'next'
import React from 'react'
import SideNav from '../components/sideNav/SideNav'
import Script from 'next/script'
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
import Reminders from '../components/Reminders'
import ResponsiveAppBar from '../components/TopNav'
import { Box, Grid } from '@mui/material'
config.autoAddCss = false;

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <Script src="https://kit.fontawesome.com/ba9dfab5fa.js" crossOrigin="anonymous"/>
      <body>
        <ResponsiveAppBar/>
        <Grid container>
          <Grid xs={2} sx={{ paddingTop: '36px' }}>
            <SideNav/>
          </Grid>
          <Grid xs={10} sx={{ paddingLeft: '25px', paddingRight: '25px' }}>
            {children}
          </Grid>
        </Grid>
      </body>
    </html>
  )
}
