import './globals.css'
import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import React from 'react'
import Nav from '../components/Nav'

const metrophobic = Montserrat({
  subsets: ['latin'],
  display: 'swap',
  weight: '400'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={metrophobic.className}>
        <Nav/>
        {children}
      </body>
    </html>
  )
}
