import './globals.css'
import type { Metadata } from 'next'
import React from 'react'
import SideNav from '../components/sideNav/SideNav'
import Script from 'next/script'
import Reminders from '../components/Reminders'
import ResponsiveAppBar from '../components/TopNav'
import { Box, Grid } from '@mui/material'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body>
        <ResponsiveAppBar/>
        <Grid container>
          <Grid xs={1} item={true} sx={{ paddingTop: '18px' }}>
            <SideNav/>
          </Grid>
          <Grid xs={9} item={true}>
            <Box sx={{ paddingTop: '18px', paddingX: '18px' }}>
              {children}
            </Box>
          </Grid>
          <Grid xs={2} item={true} sx={{ paddingTop: '18px' }}>
            <Reminders />
          </Grid>
        </Grid>
      </body>
    </html>
  )
}
