import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { useEffect, useState } from "react";

export default function Home() {
  const [data, setData] = useState([]);
  useEffect(() => {
      fetch('http://127.0.0.1:8000/api/plans/')
      .then((res) => res.json())
      .then((data) => setData(data))
      .catch((error) => {
        console.error("Error fetching data:", error);
      });
  }, []);
  console.log(data);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Teachr Lounge
        </h1>

        { data.length > 0 ?
          data.map((data) => (
            <>
              <p>{data.grade}</p>
              <p>{data.subject}</p>
            </>
          )) :
          <p>Loading ...</p>
        }

      </main>

      <footer className={styles.footer}>
        footer
      </footer>
    </div>
  )
}